<H1><center>EE 658/758 Machine Learning in Engineering</center></H1>
<H2><center>Assignment #3: Logistic Regression</center></H2>
<H2><center>Due date: Monday, february 28, 2022</center></H2>

<H3>For this assignment, you are asked to implement the logistic regression algorithm for classifying data. 
The data is in the file "adult-dataset.csv". It was extracted from the census bureau database, found at: 
    http://www.census.gov/ftp/pub/DES/www/welcome.html
<P>
The features collected about the adult individuals consists of the list below. For each feature, the possible values
that can be assigned are listed along side each feature.
</P>
"Income" is the dependent variable that we will be trying to predict as to whether an individual has an income
greater than $50,000 a year or not, based on the features of the individual.
<P>

We want to use the Scikit-Learn library to classify the data, as ndicated in the cells below.</H3>
<P>
<H4>
The list of features are:<BR>
<P>
 1- <B>age</B>: continuous<BR>
 
<P>
 2- workclass:<BR>
	Private<BR>
	Self-emp-not-inc<BR>
	Self-emp-inc<BR>
	Federal-gov<BR>
	Local-gov<BR>
	State-gov<BR>
	Without-pay<BR>
	Never-worked<BR>
    
<P>
 3- education: <BR>
	Bachelors, <BR>
	Some-college, <BR>
	11th, <BR>
	HS-grad, <BR>
	Prof-school, <BR>
	Assoc-acdm, <BR>
	Assoc-voc, <BR>
	9th, <BR>
	7th-8th, <BR>
	12th, <BR>
	Masters, <BR>
	1st-4th, <BR>
	10th, <BR>
	Doctorate, <BR>
	5th-6th, <BR>
	Preschool <BR> 
<P>
 4- marital-status: <BR>
	Married-civ-spouse,<BR>
	Divorced,<BR>
	Never-married,<BR>
	Separated,<BR>
	Widowed,<BR>
	Married-spouse-absent,<BR>
	Married-AF-spouse <BR>
<P>
 5- occupation: <BR>
	Tech-support, <BR>
	Craft-repair, <BR>
	Other-service, <BR>
	Sales, <BR>
	Exec-managerial, <BR>
	Prof-specialty, <BR>
	Handlers-cleaners, <BR>
	Machine-op-inspct, <BR>
	Adm-clerical, <BR>
	Farming-fishing, <BR>
	Transport-moving, <BR>
	Priv-house-serv, <BR>
	Protective-serv, <BR>
	Armed-Forces<BR>
 <P>
 6- race: <BR>
	White, <BR>
	Asian-Pac-Islander, <BR>
	Amer-Indian-Eskimo, <BR>
	Black, <BR>
	Other <BR>
 <P>
 7- sex: <BR>
	Female, <BR>
	Male <BR>
    <P>
 8- hours-per-week: continuous<BR>
 <P>
 9- native-country: <BR>
	United-States,<BR>
	Cambodia,<BR>
	England,<BR>
	Puerto-Rico,<BR>
	Canada,<BR>
	Germany,<BR>
	Outlying-US(Guam-USVI-etc),<BR>
	India,<BR>
	Japan,<BR>
	Greece,<BR>
	South,<BR>
	China,<BR>
	Cuba,<BR>
	Iran,<BR>
	Honduras,<BR>
	Philippines,<BR>
	Italy,<BR>
	Poland,<BR>
	Jamaica,<BR>
	Vietnam,<BR>
	Mexico,<BR>
	Portugal,<BR>
	Ireland,<BR>
	France,<BR>
	Dominican-Republic,<BR>
	Laos,<BR>
	Ecuador,<BR>
	Taiwan,<BR>
	Haiti,<BR>
	Columbia,<BR>
	Hungary,<BR>
	Guatemala,<BR>
	Nicaragua,<BR>
	Scotland,<BR>
	Thailand,<BR>
	Yugoslavia,<BR>
	El-Salvador,<BR>
	Trinadad&Tobago,<BR>
	Peru,<BR>
	Hong,<BR>
	Holand-Netherlands<BR>
 <P>
 10- Income:<BR>
	<=50K,<BR>
	>50K <BR>
 <P>

### 1. Import Libraries

In [181]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

### 2. Read data from the CSV file

In [182]:
data_path = r"C:\Users\schmi\EE658\EE658-Machine-Learning\Logistic Regression\adult-dataset.csv"
df= pd.read_csv(data_path)

### 3. Explore the data

In [183]:
df.head()
#print(df.head(1).shape)

age   workClass      Education       marital-status          occupation  \
0   25     Private           11th        Never-married   Machine-op-inspct   
1   38     Private        HS-grad   Married-civ-spouse     Farming-fishing   
2   28   Local-gov     Assoc-acdm   Married-civ-spouse     Protective-serv   
3   44     Private   Some-college   Married-civ-spouse   Machine-op-inspct   
4   34     Private           10th        Never-married       Other-service   

     race    sex  hours-per-week  Native Country   Income  
0   Black   Male              40   United-States   <=50K.  
1   White   Male              50   United-States   <=50K.  
2   White   Male              40   United-States    >50K.  
3   Black   Male              40   United-States    >50K.  
4   White   Male              30   United-States   <=50K.

### 4. print out the unique (distinct) values for each of the attributes  

In [184]:
#print out some info to learn about the column information
df.info()
objectColumns = df.dtypes[df.dtypes == object]
text_to_num = list(objectColumns.index)
print(text_to_num)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             15060 non-null  int64 
 1   workClass       15060 non-null  object
 2   Education       15060 non-null  object
 3   marital-status  15060 non-null  object
 4   occupation      15060 non-null  object
 5   race            15060 non-null  object
 6   sex             15060 non-null  object
 7   hours-per-week  15060 non-null  int64 
 8   Native Country  15060 non-null  object
 9   Income          15060 non-null  object
dtypes: int64(2), object(8)
memory usage: 1.1+ MB
['workClass', 'Education', 'marital-status', 'occupation', 'race', 'sex', 'Native Country', 'Income']


In [185]:
#play around with the notes from class
df['Education'].nunique()
print(df['Education'].unique())

sample = text_to_num[2]
print(sample)
print(df[sample])

[' 11th' ' HS-grad' ' Assoc-acdm' ' Some-college' ' 10th' ' Prof-school'
 ' 7th-8th' ' Bachelors' ' Masters' ' 5th-6th' ' Assoc-voc' ' 9th'
 ' Doctorate' ' 12th' ' 1st-4th' ' Preschool']
marital-status
0              Never-married
1         Married-civ-spouse
2         Married-civ-spouse
3         Married-civ-spouse
4              Never-married
                ...         
15055          Never-married
15056               Divorced
15057     Married-civ-spouse
15058               Divorced
15059     Married-civ-spouse
Name: marital-status, Length: 15060, dtype: object


In [186]:
for i in range(len(text_to_num)):
    col_name = text_to_num[i]
    print("\nthere are " + str(df[col_name].nunique()) +" different types in the column "+ col_name +":\n")
    print(df[col_name].unique())


there are 7 different types in the column workClass:

[' Private' ' Local-gov' ' Self-emp-not-inc' ' Federal-gov' ' State-gov'
 ' Self-emp-inc' ' Without-pay']

there are 16 different types in the column Education:

[' 11th' ' HS-grad' ' Assoc-acdm' ' Some-college' ' 10th' ' Prof-school'
 ' 7th-8th' ' Bachelors' ' Masters' ' 5th-6th' ' Assoc-voc' ' 9th'
 ' Doctorate' ' 12th' ' 1st-4th' ' Preschool']

there are 7 different types in the column marital-status:

[' Never-married' ' Married-civ-spouse' ' Widowed' ' Separated'
 ' Divorced' ' Married-spouse-absent' ' Married-AF-spouse']

there are 14 different types in the column occupation:

[' Machine-op-inspct' ' Farming-fishing' ' Protective-serv'
 ' Other-service' ' Prof-specialty' ' Craft-repair' ' Adm-clerical'
 ' Exec-managerial' ' Tech-support' ' Sales' ' Priv-house-serv'
 ' Transport-moving' ' Handlers-cleaners' ' Armed-Forces']

there are 5 different types in the column race:

[' Black' ' White' ' Other' ' Amer-Indian-Eskimo' ' As

### 5. Replace the attributes with categorical values by columns (one per value) 

In [187]:
New_df = pd.get_dummies(df,columns=text_to_num)
print(New_df.head())
print(New_df.head(1).shape)

   age  hours-per-week  workClass_ Federal-gov  workClass_ Local-gov  \
0   25              40                       0                     0   
1   38              50                       0                     0   
2   28              40                       0                     1   
3   44              40                       0                     0   
4   34              30                       0                     0   

   workClass_ Private  workClass_ Self-emp-inc  workClass_ Self-emp-not-inc  \
0                   1                        0                            0   
1                   1                        0                            0   
2                   0                        0                            0   
3                   1                        0                            0   
4                   1                        0                            0   

   workClass_ State-gov  workClass_ Without-pay  Education_ 10th  ...  \
0                  

### 6. Define your X and y Dataframes

In [197]:
#we are trying to predict income based on all the other factors
X = New_df.copy()
#X.info()
X.head(5)
X.drop(X.filter(regex='Income').columns, axis=1, inplace=True)
X.head(5)

age  hours-per-week  workClass_ Federal-gov  workClass_ Local-gov  \
0   25              40                       0                     0   
1   38              50                       0                     0   
2   28              40                       0                     1   
3   44              40                       0                     0   
4   34              30                       0                     0   

   workClass_ Private  workClass_ Self-emp-inc  workClass_ Self-emp-not-inc  \
0                   1                        0                            0   
1                   1                        0                            0   
2                   0                        0                            0   
3                   1                        0                            0   
4                   1                        0                            0   

   workClass_ State-gov  workClass_ Without-pay  Education_ 10th  ...  \
0                     0                       0                0  ...   
1                     0                       0                0  ...   
2                     0                       0                0  ...   
3                     0                       0                0  ...   
4                     0                       0                1  ...   

   Native Country_ Portugal  Native Country_ Puerto-Rico  \
0                         0                            0   
1                         0                            0   
2                         0                            0   
3                         0                            0   
4                         0                            0   

   Native Country_ Scotland  Native Country_ South  Native Country_ Taiwan  \
0                         0                      0                       0   
1                         0                      0                       0   
2                         0                      0                       0   
3                         0                      0                       0   
4                         0                      0                       0   

   Native Country_ Thailand  Native Country_ Trinadad&Tobago  \
0                         0                                0   
1                         0                                0   
2                         0                                0   
3                         0                                0   
4                         0                                0   

   Native Country_ United-States  Native Country_ Vietnam  \
0                              1                        0   
1                              1                        0   
2                              1                        0   
3                              1                        0   
4                              1                        0   

   Native Country_ Yugoslavia  
0                           0  
1                           0  
2                           0  
3                           0  
4                           0  

[5 rows x 93 columns]

In [218]:
income_column = df["Income"]
y=income_column.copy()                   
y.head(5)
y_50 = pd.get_dummies(y)
print(y_50.head())
del y_50[y_50.columns[-1]]
print(y_50.head())
print(y_50.shape)
y_50.values.reshape(-1)

    <=50K.   >50K.
0        1       0
1        1       0
2        0       1
3        0       1
4        1       0
    <=50K.
0        1
1        1
2        0
3        0
4        1
(15060, 1)


array([1, 1, 0, ..., 1, 1, 0], dtype=uint8)

### 7. Normalize the data

In [219]:
normalized data in the iris dataset practice?
normalized_X=(X-X.min())/(X.max()-X.min())
print(normalized_X.head())
print(normalized_X.head(1).shape)
#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#Xstd = scaler.fit_transform(X)
#print(Xstd[:2])

Object `practice` not found.
        age  hours-per-week  workClass_ Federal-gov  workClass_ Local-gov  \
0  0.109589        0.397959                     0.0                   0.0   
1  0.287671        0.500000                     0.0                   0.0   
2  0.150685        0.397959                     0.0                   1.0   
3  0.369863        0.397959                     0.0                   0.0   
4  0.232877        0.295918                     0.0                   0.0   

   workClass_ Private  workClass_ Self-emp-inc  workClass_ Self-emp-not-inc  \
0                 1.0                      0.0                          0.0   
1                 1.0                      0.0                          0.0   
2                 0.0                      0.0                          0.0   
3                 1.0                      0.0                          0.0   
4                 1.0                      0.0                          0.0   

   workClass_ State-gov  workClas

### 8. Split the data into testing and training subsets

In [220]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(normalized_X, y_50, test_size=0.3, random_state=45)

### 9. Train a One-Versus-One logistic regression model on the normalized training data

In [221]:
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC

In [223]:
ovoc=OneVsOneClassifier(LinearSVC(max_iter=2000, random_state=2))
ovoc.fit(X_train,y_train.values.ravel())

OneVsOneClassifier(estimator=LinearSVC(max_iter=2000, random_state=2))

In [224]:
ovocPred = ovoc.predict(X_test)

### 10. Compute the Confusion Matrix, using the One-Versus-One model and the testing data set

In [225]:
from sklearn import metrics
cmOVO= metrics.confusion_matrix(y_test, ovocPred)
print(cmOVO)

[[ 608  500]
 [ 266 3144]]


### 11. Train a One-Vs-Rest logistic regression model on the normalized training data

In [227]:
from sklearn.linear_model import LogisticRegression
ovr = LogisticRegression(random_state=15, multi_class='ovr', solver='lbfgs', max_iter=2000)
ovr.fit(X_train, y_train.values.ravel())

LogisticRegression(max_iter=2000, multi_class='ovr', random_state=15)

In [228]:
ovrPred = ovr.predict(X_test)

### 12. Compute the Confusion Matrix, using then One-Vs-Rest model and the testing data set

In [229]:
cmOVR= metrics.confusion_matrix(y_test, ovrPred)
print(cmOVR)

[[ 603  505]
 [ 261 3149]]


### 13. Compare the results of the One-Versus-One and One-Vs-Rest models

In [230]:
print(ovocPred.shape)
ovo_result = pd.DataFrame(np.array(ovocPred).reshape(-1,1))
print(ovo_result.shape)
print(ovrPred.shape)
ovr_result = pd.DataFrame(np.array(ovrPred).reshape(-1,1))

results = pd.concat([ovo_result, ovr_result], axis=1)
final = cmOVO-cmOVR
print(final) #---need to come back


(4518,)
(4518, 1)
(4518,)
[[ 5 -5]
 [ 5 -5]]


### 14. Compute the following metrics for the One-Vs-Rest model:
- Accuracy
- Error
- Sensitivity
- False Positive
- Specificity
- Precision
- Prevalence
- F1 Score

In [232]:
from sklearn.metrics import accuracy_score, f1_score, precision_score
from sklearn.metrics import confusion_matrix
tn, fp, fn, tp = confusion_matrix(y_test,ovrPred).ravel()

accuracy = accuracy_score(y_test, ovrPred)
print('accuracy = ', accuracy)
sensitivity = tp/(tp+fn)
print('sensitivity = ', sensitivity)
#false_positive = abs(y_test-ovrPred).sum()
#print('false positive = ', false_positive)
specificity = tn / (tn+fp)
print('specificity = ', specificity)
precision = precision_score(y_test, ovrPred)
print('precision = ', precision)
Population = tn+fp+fn+tp
prevalence = round( (tp+fp) / Population,2)
print('prevelance = ', prevalence)
f1 = f1_score(y_test, ovrPred)
print('f1 = ', f1)

accuracy =  0.8304559539619301
sensitivity =  0.9234604105571848
specificity =  0.5442238267148014
precision =  0.8617952928297756
prevelance =  0.81
f1 =  0.8915628539071347


### 15. Make up 2 instances of input data.Use both models to predict the classification of each data

In [233]:
ex1=New_df.iloc[15]
ex3 = New_df.iloc[2]
print(ex1)
print(ex1.shape)
ex1n = ex1[:-2]
print(ex1n.shape)
print(ex1n)
print(ex1n.dtype)

age                              37
hours-per-week                   20
workClass_ Federal-gov            0
workClass_ Local-gov              0
workClass_ Private                1
                                 ..
Native Country_ United-States     1
Native Country_ Vietnam           0
Native Country_ Yugoslavia        0
Income_ <=50K.                    1
Income_ >50K.                     0
Name: 15, Length: 95, dtype: int64
(95,)
(93,)
age                                37
hours-per-week                     20
workClass_ Federal-gov              0
workClass_ Local-gov                0
workClass_ Private                  1
                                   ..
Native Country_ Thailand            0
Native Country_ Trinadad&Tobago     0
Native Country_ United-States       1
Native Country_ Vietnam             0
Native Country_ Yugoslavia          0
Name: 15, Length: 93, dtype: int64
int64


In [238]:
#they are now 21 years old and work 45 hours a week in local government in the united states
ex1n[0]=21
ex1n[1]=45
ex1n[2]=0
ex1n[3]=1
ex1n[4]=0
print(ex1n)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [239]:
ex1n=np.array(ex1n).reshape(1,-1)
#ex3n = np.array(ex3[:-2]).reshape(1,-1)

In [240]:
#now they are 50 years old, work in the private sector for 50 hours a week in Yugoslavia
ex2n = ex1n.copy()
ex2n[0,1]=50
ex2n[0,0]=40
ex2n[0,-3]=0
ex2n[0,-1]=1
print(ex2n)

[[40 50 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21
  21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21
  21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21
  21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21  0 21  1]]


In [236]:
array = np.concatenate((ex1n, ex2n))
new_ex = pd.DataFrame(array, columns=list(X.columns))
print(new_ex.head())

   age  hours-per-week  workClass_ Federal-gov  workClass_ Local-gov  \
0   37              20                       0                     0   
1   40              50                       0                     0   

   workClass_ Private  workClass_ Self-emp-inc  workClass_ Self-emp-not-inc  \
0                   1                        0                            0   
1                   1                        0                            0   

   workClass_ State-gov  workClass_ Without-pay  Education_ 10th  ...  \
0                     0                       0                0  ...   
1                     0                       0                0  ...   

   Native Country_ Portugal  Native Country_ Puerto-Rico  \
0                         0                            0   
1                         0                            0   

   Native Country_ Scotland  Native Country_ South  Native Country_ Taiwan  \
0                         0                      0                

In [241]:
ovr_final = ovr.predict(new_ex)
ovo_final = ovoc.predict(new_ex)
print('the predictions are ovr and ovo :', ovr_final, ovo_final)

the predictions are ovr and ovo : [0 0] [0 0]


## END